#!/usr/bin/env python3
"""Assemble every asm/*.s into pokeldn/frlg/rom/buffer_payloads.py.

    ./scripts/gen_buffer_scripts.py [--check]

The bytes are committed so a live host needs no GBA toolchain; tests/test_buffer_script.py
re-assembles and compares when arm-none-eabi-as is installed.
"""

import argparse
import hashlib
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from pokeldn.frlg.rom import custom_code  # noqa: E402

ASM_DIR = ROOT / "asm"
OUT = ROOT / "pokeldn" / "frlg" / "rom" / "buffer_payloads.py"


def assemble(source_path):
    """Assemble one ARM source to raw bytes. Raises CodeError without a toolchain."""
    return custom_code.assemble(source_path.read_text())


def render():
    lines = [
        '"""Generated by scripts/gen_buffer_scripts.py from asm/*.s. Do not edit by hand."""',
        "",
        "# name -> (ARM machine code, sha256 of the asm source it was assembled from)",
        "PAYLOADS = {",
    ]
    for source in sorted(ASM_DIR.glob("*.s")):
        code = assemble(source)
        digest = hashlib.sha256(source.read_bytes()).hexdigest()
        lines.append(f"    {source.stem!r}: (")
        lines.append(f"        bytes.fromhex({code.hex()!r}),")
        lines.append(f"        {digest!r},")
        lines.append("    ),")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the committed module is stale")
    args = parser.parse_args()
    text = render()
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print(f"{OUT} is stale; re-run ./scripts/gen_buffer_scripts.py", file=sys.stderr)
            return 1
        print(f"{OUT} is up to date")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
